In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append('/home/pepijn/Documents/uni/y5/thesis/amalur/amalur-experiments/amalur-factorization')

from datasets.tpc_ai.load import load_usecase_01


/tmp/ipykernel_105517/2532907207.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
2024-02-11 12:14:35.288 | ERROR    | amalur.AmalurMatrix:<module>:20 - USE_MKL set to True, but could not import sparse_dot_mkl. Falling back to USE_MKL=False
Traceback (most recent call last):

  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 

In [2]:
amalur, T = load_usecase_01("./data")

2024-02-11 12:14:35.304 | INFO     | datasets.tpc_ai.load:load_usecase_01:29 - Loading data for usecase01
2024-02-11 12:14:35.306 | DEBUG    | datasets.tpc_ai.load:load_usecase_01:34 - Start reading order_path='./data/order.csv'
2024-02-11 12:14:35.312 | DEBUG    | datasets.tpc_ai.load:load_usecase_01:36 - Start reading lineitem_path='./data/lineitem.csv'
2024-02-11 12:14:35.314 | DEBUG    | datasets.tpc_ai.load:load_usecase_01:38 - Start reading order_returns_path='./data/order_returns.csv'
2024-02-11 12:14:35.316 | DEBUG    | datasets.tpc_ai.load:load_usecase_01:40 - Finished reading data
2024-02-11 12:14:35.327 | INFO     | datasets.tpc_ai.load:load_usecase_01:67 - Finished preprocessing for usecase10, now creating matrices
2024-02-11 12:14:35.328 | INFO     | datasets.tpc_ai.load:create_AmalurMatrix:113 - Creating Mapping and Indicator matrices for source 0 with 3 rows
2024-02-11 12:14:35.329 | DEBUG    | datasets.tpc_ai.load:create_AmalurMatrix:114 -    row_number_order  o_order_i

In [14]:
display(T)
display(pd.DataFrame(amalur.materialize().todense()))
print("difference: " , np.sum(np.abs((T.values - amalur.materialize().todense()))))

o_order_id  o_customer_sk  invoice_year  quantity  price  row_price  \
0           1             11          2024         2     20         40   
1           1             11          2024         1     25         25   
2           2             12          2024         3     13         39   
3           3             11          2024         1     10         10   

   or_return_quantity  
0                 0.0  
1                 0.0  
2                 0.0  
3                 1.0

0     1       2    3     4     5    6
0  1.0  11.0  2024.0  2.0  20.0  40.0  0.0
1  1.0  11.0  2024.0  1.0  25.0  25.0  0.0
2  2.0  12.0  2024.0  3.0  13.0  39.0  0.0
3  3.0  11.0  2024.0  1.0  10.0  10.0  1.0

difference:  0.0


In [5]:
for x in amalur.S:
    print(x.todense())

[[   1   11 2024]
 [   2   12 2024]
 [   3   11 2024]]
[[ 2 20 40]
 [ 1 25 25]
 [ 3 13 39]
 [ 1 10 10]]
[[1.]]


In [6]:
for x in amalur.I:
    print(x.todense())

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0]
 [0]
 [0]
 [1]]


In [7]:
for x in amalur.M:
    print(x.todense())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
